# Atlas Micro Platform Inventory
# ⚠️ This is a demo inventory file with placeholder values

all:
  vars:
    # Global variables for all hosts
    ansible_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/atlas-key.pem
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # Project-specific variables
    project_name: atlas-micro
    environment: "{{ env | default('dev') }}"
    cluster_name: "{{ project_name }}-{{ environment }}"
    region: eu-west-1

  children:
    # Bastion hosts for secure access to private resources
    bastion:
      hosts:
        bastion-dev:
          ansible_host: 1.2.3.4  # Replace with actual bastion IP
          environment: dev
        bastion-stage:
          ansible_host: 1.2.3.5  # Replace with actual bastion IP
          environment: stage
        bastion-prod:
          ansible_host: 1.2.3.6  # Replace with actual bastion IP
          environment: prod
      vars:
        ansible_user: ec2-user
        role_type: bastion

    # EKS worker nodes (if direct access needed)
    # Usually not needed as we use kubectl through bastion
    eks_nodes:
      hosts:
        # These would be populated dynamically in real scenarios
        # eks-node-dev-1:
        #   ansible_host: 10.0.1.10
        #   environment: dev
        # eks-node-dev-2:
        #   ansible_host: 10.0.1.11
        #   environment: dev
      vars:
        ansible_user: ec2-user
        role_type: eks_node

    # Environment-specific groups
    development:
      children:
        bastion:
        eks_nodes:
      vars:
        environment: dev
        cluster_name: atlas-micro-dev
        
    staging:
      children:
        bastion:
        eks_nodes:
      vars:
        environment: stage
        cluster_name: atlas-micro-stage
        
    production:
      children:
        bastion:
        eks_nodes:
      vars:
        environment: prod
        cluster_name: atlas-micro-prod

# Example of how to use this inventory:
#
# Run playbook for all environments:
# ansible-playbook -i inventory/hosts.yml playbooks/site.yml
#
# Run playbook for specific environment:
# ansible-playbook -i inventory/hosts.yml playbooks/site.yml -l development
#
# Run playbook for bastion hosts only:
# ansible-playbook -i inventory/hosts.yml playbooks/bastion.yml -l bastion
#
# Run with specific environment variable:
# ansible-playbook -i inventory/hosts.yml playbooks/site.yml -e env=prod
